name: "hello world"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World action
    - uses: kaych22/my-Github-action@v1
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: kaych22/my-Github-action@v1
    - uses: ./
      with:
        milliseconds: 1000